### ISSUE TITLE
Short running program

### ISSUE THREAD

**Issue by MaxBittker** [agermanidis/livepython#1]
How would I use livepython to examine a short running program like an algorithm example? It seemed to exit immediately

**Comment by meain** [comment]
@agermanidis How about implementing line by line tracing which can be enabled with a separate argument? Also slow down the execution in this mode?

**Comment by agermanidis** [comment]
@MaxBittker try installing the new version (0.0.4), execution should be slow by default now. (You can switch between slow/fast execution with the left/right arrow).

**Comment by MaxBittker** [comment]
awesome, thanks 👍
