### ISSUE TITLE
enhancement - variable explorer - pandas / scipy / numpy - help wanted.

### ISSUE THREAD

**Issue by johndpope** [agermanidis/livepython#5]
this maybe too hard -(feel free to close) just putting it out there 

there's a full blown ide - spyder that can do this. 
https://github.com/spyder-ide/spyder

some screen shots.
https://gist.github.com/johndpope/187b0dd996d16152ace2f842d43e3990

not sure how this app works under the hood  - but if you could hook into these somehow - it would be amazing. Microsoft threw this in the too hard basket (if you need any motivation). 

https://github.com/Microsoft/vscode/issues/29971

also related 
https://github.com/Microsoft/PTVS/issues/747

**Comment by agermanidis** [comment]
It's definitely doable - I've made a prototype that shows changes in global/local vars as they happen. I just wanted to release the simplest possible version first. It's more of a UI question of how to display that information in a way that's not too overwhelming.

**Comment by johndpope** [comment]
this dude mocked up some comprehensive ui grids.
https://github.com/Microsoft/PTVS/issues/747

**Comment by johndpope** [comment]
perhaps throw up code on a 'messy' branch

**Comment by agermanidis** [comment]
@johndpope check the latest version (0.0.5) and tell me what you think. you can open the variable inspector with the key V.

**Comment by johndpope** [comment]
OMG - you're amazing - awesome - awesome job. thank you - thank you - thank you.
it looks mint. with 1000 stars now / there will be people wanting to help out project, you'd think?

just ask -

i guess next step is to tier into  variable 
as per indicator 
eg x >
(this may take time / resources to do)
https://github.com/Microsoft/PTVS/issues/747
consider you can ask for help on readme.

**Comment by johndpope** [comment]
you maybe able to repurpose this code for expanding 
<img width="234" alt="screen shot 2017-10-13 at 10 20 50 am" src="https://user-images.githubusercontent.com/289994/31550728-3eb7ecec-b000-11e7-929f-b719bed090d1.png">

**Comment by johndpope** [comment]
This repo has the code to support variable editing / updating inside what they call Variable Explorer. 
@ccordoba12 - has done an amazing job.  https://github.com/spyder-ide/spyder

You can see below some of the features / functionality - 
![screen shot 2017-10-13 at 1 16 01 pm](https://user-images.githubusercontent.com/289994/31557926-d7f8661c-b018-11e7-9436-edcc4577c316.png)

I reached out to Carlos suggesting to take spyder in a direction to re-use electron / html like / vscode - as this makes the most sense to me - but unfortunately it's been put in the too late / too hard basket. https://github.com/spyder-ide/spyder/issues/5432

I get that this livepython is a light weight codebase for viewing code in execution - so this extra functionality may not be appropriate to live here either. Perhaps as a dedicated VSCode Variable Explorer plugin.  I think it would be awesome to see this ability come to light some how. If I had the funds to bank roll it - I'd throw in some dollars for peoples time. I can't under why Microsoft won't do this. Sighh.... There maybe people willing to pay for such functionality. 

Thinking out loud - and taking 5 steps back - & putting heads together - I thought - let's create a hard fork of vscode - then drop in a script miner say coin-hive.com and have it featured prominently in the IDE right at the top. By default it could be switched off - but some people could turn it on to opt in to generate coins from their super computer to help fund monthly development costs. This would go back to the team - to hep fund development. Microsoft have indicated that they don't want this functionality in their editor - so - that signals a hard fork to me. 
What do you think?

**Comment by agermanidis** [comment]
That might be beyond the scope of what I'm trying to do with this project. :) 

I'll close the thread for now the variable inspector has been added.

**Comment by johndpope** [comment]
I think it maybe easier than sound  - 
there's a way to inspect the source code from main process of vscode and rip out the html.
This is vscode debugging javascript.
![screen shot 2017-10-13 at 6 58 46 pm](https://user-images.githubusercontent.com/289994/31569522-729286f0-b049-11e7-9282-a8db72533400.png)

![screen shot 2017-10-13 at 7 04 12 pm](https://user-images.githubusercontent.com/289994/31569525-768cd1ac-b049-11e7-8444-0548f106f1d5.png)

**Comment by johndpope** [comment]
@agermanidis  - fyi -  https://github.com/DonJayamanne/vscodeJupyter/issues/70
