### ISSUE TITLE
她她她

### ISSUE THREAD

**Issue by YXeric** [agermanidis/livepython#6]
便于大家了解

**Comment by YXeric** [comment]
@meain 有什么好的建议

**Comment by YXeric** [comment]
> 有什么好的建议

jiddejifodjf

**Comment by YXeric** [comment]
> 这个问题前面讨论过了

https://github.com/agermanidis/livepython/issues/6#issuecomment-335418149

**Comment by meain** [comment]
我不明白你在说什么
