### ISSUE TITLE
README gif is disorienting

### ISSUE THREAD

**Issue by mgalgs** [agermanidis/livepython#7]
Just a bit of candid feedback...  Seems like an awesome project, but the gif on the README is really confusing...  I can't tell if you're scrolling up and down to show different lines lighting up?  I also find myself trying to understand the intent of the source code itself, which, of course, is a fool's errand with all the jumping around.

What about using a simple, short program to showcase the program?  Maybe a simple Euler problem or something like that.

**Comment by agermanidis** [comment]
That's fair feedback. I agree that the current GIF is a bit disorienting / confusing. I'll put up a better one soon. Thanks!

**Comment by agermanidis** [comment]
I updated the gif - the function of the app should be more clear now (GIF demonstrates line-by-line tracing and is tracking variables). 

I was considering using a simple Euler program but I want to show that Livepython can assist people with the kinds of ML/DS tasks that are the primary use of Python nowadays.

**Comment by mgalgs** [comment]
Very nice!!! :tada:
